# syntax=docker/dockerfile:1
FROM ruby:3.0.2

RUN apt-get update -qq && apt-get install -y curl

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
RUN apt-get update -qq && apt-get install -y \
                              postgresql-client \
                              yarn \
                              nodejs \
                              tzdata

RUN mkdir /walletman
WORKDIR /walletman
COPY Gemfile /walletman/Gemfile
COPY Gemfile.lock /walletman/Gemfile.lock
RUN bundle install

# Configure the main process to run when running the image
# CMD ["rails", "server", "-b", "0.0.0.0"]
